### ISSUE TITLE
A user should be able to have multiple projects they can add a todo

### ISSUE THREAD

**Issue by jrzerr** [sean-keisuke/React-Practice#17]
We'll start from the server and complete at the frontend for this project.  It's a common pattern to start data first then UI last.

From the data side, we'd like to have a Todo belong to a Project.  Just a single project.

So a Project has many Todos.  A Todo has one project.  This is a one to many relationship.

1) Figure out how to create a model in Django for Project and create the relation between the existing model Todo and the new Project model.

  * you will create the Project model, and add a new field to Todo for the relationship
  * after that we will let Django create the appropriate database migrations to add the new table and new column.  Read up on Django migrations, how to make them using "makemigrations" and how to apply it using "migrate".
  * it's important to realize that we have existing Todos, what happens when we run the migration on existing Todos?  The existing ones don't have a project.  How do we handle that?

2) Add a new endpoint for projects

2.5) Add the project into the API output for the existing todos endpoint

3) Add a filter for Todos so we can select todos that belong to a specific project when we call the todos endpoint

4) Add a Projects dropdown in the frontend populated from the API so you pick a project when you add a todo

5) Add the Project name to the display of each Todo

**Comment by sean-keisuke** [comment]
Haven't implemented 4 yet
